# Document classification

In [31]:
import numpy as np

In [32]:
def loadDataset():
    postingList = [['my', 'dog', 'has', 'flea', \
'problems', 'help', 'please'],
['maybe', 'not', 'take', 'him', \
'to', 'dog', 'park', 'stupid'],
['my', 'dalmation', 'is', 'so', 'cute', \
'I', 'love', 'him'],
['stop', 'posting', 'stupid', 'worthless', 'garbage'],
['mr', 'licks', 'ate', 'my', 'steak', 'how',\
'to', 'stop', 'him'],
['quit', 'buying', 'worthless', 'dog', 'food', 'stupid']]
    classVec = [0,1,0,1,0,1]
    return postingList,classVec

In [33]:
def createVocablist(dataset):
    vocabSet = set([])
    for document in dataset:
        vocabSet = vocabSet|set(document)
    return list(vocabSet)

In [34]:
def setOfWord2Vec(vocabList,inputSet):
    returnVec = [0]*len(vocabList)
    for word in inputSet:
        if word in vocabList:
            returnVec[vocabList.index(word)] += 1
        else:
            print("word is not in vocab")
            
    return returnVec

In [35]:
listOfPost,listClasses = loadDataset()

In [36]:
myVocabList = createVocablist(listOfPost)

In [37]:
len(setOfWord2Vec(myVocabList,listOfPost[0]))

32

In [38]:
def trainNB(trainMatrix, trainCategory):
    numTrainDocs = len(trainMatrix)
    numwords = len(trainMatrix[0])
    pAbusive = sum(trainCategory)/float(numTrainDocs)
    p0Num = np.ones(numwords)
    p1Num = np.ones(numwords)
    p0Denom = 2.0
    p1Denom = 2.0
    for i in range (numTrainDocs):
        if trainCategory[i] == 1:
            p1Num += trainMatrix[i]
            p1Denom += sum(trainMatrix[i])
        else:
            p0Num += trainMatrix[i]
            p0Denom += sum(trainMatrix[i])
    p1Vect = np.log(p1Num/p1Denom)
    p0Vect = np.log(p0Num/p1Denom)
    return p1Vect,p0Vect,pAbusive
        

In [39]:
trainMat = []
for postinDoc in listOfPost:
    trainMat.append(setOfWord2Vec(myVocabList, postinDoc))

In [40]:
p0V,p1V,pAb = trainNB(trainMat,listClasses)

In [41]:
p0V

array([-3.04452244, -1.65822808, -2.35137526, -3.04452244, -2.35137526,
       -3.04452244, -3.04452244, -2.35137526, -2.35137526, -2.35137526,
       -2.35137526, -3.04452244, -2.35137526, -3.04452244, -2.35137526,
       -3.04452244, -2.35137526, -3.04452244, -3.04452244, -3.04452244,
       -2.35137526, -3.04452244, -3.04452244, -2.35137526, -2.35137526,
       -3.04452244, -3.04452244, -3.04452244, -3.04452244, -1.94591015,
       -3.04452244, -1.94591015])

In [42]:
p1V

array([-2.35137526, -3.04452244, -3.04452244, -2.35137526, -2.35137526,
       -2.35137526, -2.35137526, -2.35137526, -3.04452244, -3.04452244,
       -3.04452244, -2.35137526, -1.94591015, -2.35137526, -3.04452244,
       -2.35137526, -3.04452244, -2.35137526, -2.35137526, -2.35137526,
       -3.04452244, -2.35137526, -1.65822808, -3.04452244, -3.04452244,
       -2.35137526, -2.35137526, -2.35137526, -2.35137526, -3.04452244,
       -2.35137526, -2.35137526])

In [43]:
pAb

0.5

In [44]:
def classify(vec2Classify,p0Vec,p1Vec,pClass1):
    p1 = sum(vec2Classify*p1Vec)+ np.log(pClass1)
    p0 = sum(vec2Classify * p0Vec) + np.log(1.0 - pClass1)
    if p1>p0:
        return 1
    else:
        return 0

In [45]:
testEntry = ['love', 'my', 'dalmation']

In [46]:
thisDoc = np.array(setOfWord2Vec(myVocabList, testEntry))

In [47]:
thisDoc

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [48]:
classify(thisDoc,p0V,p1V,pAb)

1

In [49]:
testEntry = ['stupid', 'garbage', 'dalmation']

In [50]:
thisDoc = np.array(setOfWord2Vec(myVocabList, testEntry))

In [51]:
classify(thisDoc,p0V,p1V,pAb)

0

# SpamFilter

In [52]:
import glob
import re
import random

In [53]:
path = r"/home/marinex/Data analysis/Spam/*/*"

In [54]:
x= glob.glob(path)

In [55]:
is_spam = "ham" not in x[-1]

In [56]:
is_spam

True

In [57]:
data = []

In [58]:
for file in glob.glob(path):
    is_spam = "ham" not in file
    with open(file,'r',encoding='utf-8',errors = "ignore") as file:
        for line in file:
            line = line.lower()
            if line.startswith("subject:"):
                subject = re.sub(r"^subject: ","",line).strip()
                subject = re.sub(r"^re:","",subject )
                subject = re.findall("[a-z0-9']+",subject)
                data.append((list(set(subject)),is_spam))

In [59]:
split_index

NameError: name 'split_index' is not defined

In [60]:
random.shuffle(data)

In [61]:
train_data = data[:int(0.75*len(data))]
test_data = data[(int(0.75*len(data)))+1:]

In [62]:
data

[(['141', '1', '6', 'kvim'], False),
 (['mailing',
   'sourceforge',
   'lists',
   'memberships',
   'spam',
   '08',
   '00',
   'reminder',
   'net',
   'list'],
  False),
 (['re',
   'spamassassin',
   'sadev',
   '60',
   '1',
   'rules',
   '29',
   '30',
   'cf',
   'sacvs',
   'whitelist',
   'cvs'],
  False),
 (['delta',
   'automated',
   'from',
   'recovery',
   'a',
   'use',
   'of',
   'for',
   'base',
   'image'],
  False),
 (['50',
   'spamassassin',
   '1',
   'rules',
   '226',
   'scores',
   'cf',
   '227',
   'sacvs',
   'cvs'],
  False),
 (['rpm',
   'fr5',
   're',
   'problem',
   'lame',
   '3',
   '92',
   'building',
   'on',
   'rh8',
   'f',
   'src'],
  False),
 (['get', 'apt', 'question'], False),
 (['entrepreneurs'], False),
 (['googlenews'], False),
 (['dude', 'home'], False),
 (['freshrpms', 'rpm', 'zzzlist', 'net'], False),
 (['opencourseware', 'mit'], False),
 (['united', 's', 'roman', 'sed', 'empire', 'g', 'states'], False),
 (['refuses',
   'just

In [63]:
class SpamFilter:
    def __init__(self,k=1):
        self.k = k
        
    def train(self,data):
        
        
    def cal_label_

IndentationError: expected an indented block (<ipython-input-63-8173bbce1a05>, line 8)

In [64]:
data = tokenize(data)

NameError: name 'tokenize' is not defined

In [65]:
class BernoulliNB:
    def __init__(self,alpha=1.0):
        self.alpha = 1.0
        
    def fit(self,X,Y):
        self.X = self.encode_X(X)
        self.Y =Y
        self.label_Y(Y)
        self.cal_prob_label()
        self.cal_prob_feature()
        
        
    def encode_X(self,data):
        self.feature = []
        for x in data:
            for y in x:
                if y not in self.feature:
                    self.feature.append(y)
        encoded_x = []
        for x in data:
            temp = []
            for u in self.feature:
                count = 0
                for y in x:
                    if u==y:
                        count+=1
                if(count>0):
                    count=1
                temp.append(count)
            encoded_x.append(temp)
        return encoded_x
    
    def label_Y(self,data):
        self.label = []
        for y in data:
            if y not in self.label:
                self.label.append(y)
                
    def cal_prob_label(self):
        self.prob_label = {}
        for label in self.label:
            count = 0
            for y in self.Y:
                if y==label:
                    count+=1
            self.prob_label[label] = count/len(self.Y)
            
    def cal_prob_feature(self):
        self.prob_feature = {}
        for label in self.label:
            self.prob_feature[label] = {}
            for i in range(0,len(self.feature)):
                count = 0
                for x,y in zip(self.X,self.Y):
                    if y==label:
                        count+=x[i]
                self.prob_feature[label][self.feature[i]]=(count+self.alpha)/((self.prob_label[label]*len(self.Y))+(self.alpha*2))

    def predict(self,test_X):
        encoded_test_X=[]
        for x in test_X:
            for feature in self.feature:
                count = 0
                for x1 in x:
                    if x1==feature:
                        count+=1
                if(count>0):
                    count =1
                encoded_test_X.append(count)
        output = {}
        for label in self.label:
            p = self.prob_label[label]
            for x,f in zip(encoded_test_X,self.feature):
                if x==1:
                    p*=self.prob_feature[label][f]
                else:
                    p*=1-self.prob_feature[label][f]
            output[label] = np.log(p)
        return output
                    
                
                
                        


In [66]:
b = BernoulliNB()

In [67]:
feature = []
label = []

In [79]:
for data in train_data:
    feature.append(data[0])
    label.append(data[1])

In [76]:
b.fit(feature,label)

In [89]:
b.predict(train_data[29][0])

{False: -58.81145992042564, True: -62.101955257705924}

In [80]:
count =-1
for l in label:
    count+=1
    if l:
        print(count)

18
27
29
30
39
47
65
86
98
112
118
119
121
122
126
149
154
163
165
168
169
184
187
192
211
215
217
219
248
249
251
256
259
277
280
286
296
303
305
312
313
316
321
324
330
332
336
339
342
343
347
354
362
364
368
374
376
377
378
388
392
393
407
409
440
441
448
460
462
471
482
484
492
495
499
506
509
540
542
555
557
565
571
581
583
606
612
618
619
621
637
642
650
664
667
672
677
679
680
698
713
714
718
722
724
728
737
743
752
760
765
768
774
779
783
793
795
797
820
824
834
838
846
847
848
849
851
854
873
875
896
908
917
920
921
930
932
937
942
946
962
963
965
968
975
986
988
991
993
995
1007
1016
1019
1032
1041
1049
1050
1052
1053
1072
1082
1086
1100
1101
1109
1116
1117
1118
1120
1126
1129
1135
1138
1139
1144
1148
1160
1170
1171
1173
1176
1178
1185
1195
1196
1205
1215
1218
1254
1259
1262
1265
1266
1288
1294
1328
1349
1351
1363
1372
1374
1377
1378
1396
1397
1402
1432
1440
1444
1446
1452
1479
1487
1493
1502
1503
1508
1510
1516
1530
1532
1536
1542
1545
1548
1587
1590
1591
1607
1613
1618
1632

[(['141', '1', '6', 'kvim'], False),
 (['mailing',
   'sourceforge',
   'lists',
   'memberships',
   'spam',
   '08',
   '00',
   'reminder',
   'net',
   'list'],
  False),
 (['re',
   'spamassassin',
   'sadev',
   '60',
   '1',
   'rules',
   '29',
   '30',
   'cf',
   'sacvs',
   'whitelist',
   'cvs'],
  False),
 (['delta',
   'automated',
   'from',
   'recovery',
   'a',
   'use',
   'of',
   'for',
   'base',
   'image'],
  False),
 (['50',
   'spamassassin',
   '1',
   'rules',
   '226',
   'scores',
   'cf',
   '227',
   'sacvs',
   'cvs'],
  False),
 (['rpm',
   'fr5',
   're',
   'problem',
   'lame',
   '3',
   '92',
   'building',
   'on',
   'rh8',
   'f',
   'src'],
  False),
 (['get', 'apt', 'question'], False),
 (['entrepreneurs'], False),
 (['googlenews'], False),
 (['dude', 'home'], False),
 (['freshrpms', 'rpm', 'zzzlist', 'net'], False),
 (['opencourseware', 'mit'], False),
 (['united', 's', 'roman', 'sed', 'empire', 'g', 'states'], False),
 (['refuses',
   'just

In [73]:
count == 1
for data in test_data:
    if data[1]:
        count+=1

In [74]:
count

504

In [86]:
train_data[18][0]

['mvcmv', 'garden', 'ilug', 'ornaments']