# Naive Bayes II

# Multinomial NB

In [9]:
import numpy as np
from sklearn.feature_extraction import DictVectorizer
from sklearn.naive_bayes import MultinomialNB

data = [{'house':100,'street':50,'shop':25,'car':100,'tree':20},{'house':5,'street':5,'shop':0,'car':10,'tree':500,'river':1}]
dv = DictVectorizer(sparse=False)
X = dv.fit_transform(data)
Y = np.array([1,0])
mnb = MultinomialNB()
mnb.fit(X,Y)
test_data = data= [{'house':80,'street':20,'shop':15,'car':70,'tree':10,'river':1},
                  {'house': 10, 'street': 5, 'shop': 1, 'car': 8, 'tree': 300, 'river': 0}]
mnb.predict(dv.fit_transform(test_data))

array([1, 0])

In [2]:
data = [{'house':100,'street':50,'shop':25,'car':100,'tree':20},{'house':5,'street':5,'shop':0,'car':10,'tree':500,'river':1}]

In [3]:
data

[{'house': 100, 'street': 50, 'shop': 25, 'car': 100, 'tree': 20},
 {'house': 5, 'street': 5, 'shop': 0, 'car': 10, 'tree': 500, 'river': 1}]

In [4]:
dv = DictVectorizer(sparse=False)

In [5]:
X = dv.fit_transform(data)

In [6]:
X

array([[100., 100.,   0.,  25.,  50.,  20.],
       [ 10.,   5.,   1.,   0.,   5., 500.]])

In [7]:
Y = np.array([1,0])

In [8]:
mnb = MultinomialNB()

In [9]:
mnb.fit(X,Y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [10]:
test_data = data= [{'house':80,'street':20,'shop':15,'car':70,'tree':10,'river':1},
                  {'house': 10, 'street': 5, 'shop': 1, 'car': 8, 'tree': 300, 'river': 0}]

In [11]:
mnb.predict(dv.fit_transform(test_data))

array([1, 0])

In [33]:
X = [["Chinese","Beijing","Chinese"],
        ["Chinese","Chinese","Shanghai"]
        ,["Chinese","Macao"],
       ["Tokyo","Japan","Chinese"]]
Y = ["yes","yes","yes","no"]

In [34]:
def one_hot_encoding(data):
    unique = []
    for x in data:
        for y in x:
            if y not in unique:
                unique.append(y)
    one_hot_encoding = []
    for x in data:
        temp = []
        for u in unique:
            count = 0
            for y in x:
                if u==y:
                    count+=1
            temp.append(count)
        one_hot_encoding.append(temp)
    return one_hot_encoding

In [312]:
class MultinomialNB:
    def __init__(self,alpha=1.0):
        self.alpha = 1.0
        
    def fit(self,X,Y):
        x_temp,self.feature = self.encode_X(X)
        y_temp,self.label_encode,self.label = self.encode_Y(Y)
        self.X = np.array(x_temp)
        self.Y = np.array(y_temp)
        self.cal_prob_label()
        self.cal_prob_feature()
        
    def encode_X(self,data):
        unique = []
        for x in data:
            for y in x:
                if y not in unique:
                    unique.append(y)
        one_hot_encoding = []
        for x in data:
            temp = []
            for u in unique:
                count = 0
                for y in x:
                    if u==y:
                        count+=1
                temp.append(count)
            one_hot_encoding.append(temp)
        return one_hot_encoding,unique
    
    def encode_Y(self,Y):
        output = []
        unique = []
        for x in Y:
            if x not in unique:
                unique.append(x)
        count = 0
        for u in unique:
            for y in Y:
                if u==y:
                    output.append(count)
            count+=1
        label = []
        for i in range(0,count):
            label.append(i)
        return output,label,unique
    
    def cal_prob_label(self):
        self.prob_label ={}
        for l in self.label_encode:
            count = 0 
            for i in self.Y:
                if l==i:
                    count+=1
            self.prob_label[l] = count/self.Y.size
            
    def cal_prob_feature(self):
        self.prob_feature={}
        
        for u in self.label_encode:
            temp_count_feature = []
            for i in range(0,len(self.feature)):
                temp_count_feature.append(0)
            self.prob_feature[u] = {}
            n=0
            for x,y in zip(self.X,self.Y):
                if y==u:
                    for i in range(0,len(x)):
                        temp_count_feature[i]+=x[i]
                        n+=x[i]
            for i in range(0,len(self.feature)):
                temp_count_feature[i]+=self.alpha
            temp = {}
            n+=len(self.feature)
            for x,y in zip(self.feature,temp_count_feature):
                temp[x]=y/n
            self.prob_feature[u]= temp
            
    def predict(self,X):
        temp_X = []
        for x in X:
            temp = []
            for feature in self.feature:
                count = 0
                for y in x:
                    if(feature == y):
                        count+=1
                temp.append(count)
            temp_X.append(temp)
        self.test_X = np.array(temp_X)
        output = []
        for X1 in self.test_X:
            for label,label_decode in zip(self.label_encode,self.label):
                temp = {}
                p = self.prob_label[label]
                for x,feature in zip(X1,self.feature):
                    if(x!=0):
                        while(x!=0):
                            p*=self.prob_feature[label][feature]
                            x-=1
                temp[label_decode] = p
                output.append(temp)
        return output
                
                            
            
        

                
            
            
            
                    
                    
                    
                    
        
        
    
    
                
        

In [313]:
m = MultinomialNB()

In [314]:
m.fit(X,Y)

In [299]:
m.X

array([[2, 1, 0, 0, 0, 0],
       [2, 0, 1, 0, 0, 0],
       [1, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 1, 1]])

In [300]:
m.Y

array([0, 0, 0, 1])

In [301]:
m.feature

['Chinese', 'Beijing', 'Shanghai', 'Macao', 'Tokyo', 'Japan']

In [302]:
m.label

['yes', 'no']

In [303]:
m.cal_prob_label()

In [304]:
m.prob_label

{0: 0.75, 1: 0.25}

In [305]:
m.cal_prob_feature()

In [306]:
m.prob_feature

{0: {'Chinese': 0.42857142857142855,
  'Beijing': 0.14285714285714285,
  'Shanghai': 0.14285714285714285,
  'Macao': 0.14285714285714285,
  'Tokyo': 0.07142857142857142,
  'Japan': 0.07142857142857142},
 1: {'Chinese': 0.2222222222222222,
  'Beijing': 0.1111111111111111,
  'Shanghai': 0.1111111111111111,
  'Macao': 0.1111111111111111,
  'Tokyo': 0.2222222222222222,
  'Japan': 0.2222222222222222}}

In [307]:
test_X = [["Chinese","Chinese","Chinese","Tokyo","Japan"]]

In [315]:
print(m.predict(test_X))

[{'yes': 0.00030121377997263036}, {'no': 0.00013548070246744226}]


In [309]:
a

[{'yes': 0.00030121377997263036}, {'no': 0.00013548070246744226}]

In [294]:
a = np.array([1,2,3])

In [295]:
len(a)

3

In [181]:
a ={1:{1:2}}

In [182]:
a[1]

{1: 2}

In [183]:
a[1][1]

2